# Generated by Django 6.0.4 on 2026-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users_foto/'),
        ),
    ]
